BOARD = TEX_SHURA

MCU = cortex-m0plus
MCU_FAMILY = HT32
MCU_SERIES = HT32F523xx
MCU_STARTUP = ht32f523xx
MCU_LDSCRIPT = HT32F5235x
ARMV = 6

BOOTLOADER = custom

MOUSEKEY_ENABLE = yes
PS2_MOUSE_ENABLE = yes
PS2_ENABLE = yes
PS2_DRIVER = interrupt

EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

SRC += hal_pal_lld_exti.c
