BOARD = TEX_SHURA

MCU = cortex-m0plus
MCU_FAMILY = HT32
MCU_SERIES = HT32F523xx
MCU_STARTUP = ht32f523xx
MCU_LDSCRIPT = HT32F5235x
ARMV = 6

BOOTLOADER = custom

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
